FROM nikolaik/python-nodejs:python3.8-nodejs14 AS builder
WORKDIR /src
COPY . .
RUN npm install && \
    npm run build && \
    rm -rf node_modules && \
    npm ci --only=production

FROM nikolaik/python-nodejs:python3.8-nodejs14
COPY --from=builder /src/build /src/build
COPY --from=builder /src/node_modules /src/node_modules
RUN pip install requests
WORKDIR /src
CMD ["/src/build/server/index.js"]
